[AWS]
bucket_s3=s3://game-recommender-algorithm
aws_access_key_id=ASIA2F6DUCXGZQ5LFOWL
aws_secret_access_key=dwxq3vxemFBSknMsAGNmGgajGmJuiznVRNNnRnM9
aws_session_token=FwoGZXIvYXdzENv//////////wEaDAb9BZEpZcwBoZ3IVyLBAfYq9ruoT1oHa7ceMce0m2Ic/0wudKGEyeQDavB9ksOmaG99wEAAibbPGN7C/zRovxJUm43wNSL/TOdjbZYOazIijbwfJ9FeZvGfP0o8AcDOznJ965eUuqprCI0NntZqAtLIoImUVjzsQiRoqf4rQtZ+wfbT1goK4/tF/JWTd9c2lU4+LaMP3xEq/q1vMv4S2ywhnrMI5dcaVIvk/p8iylKKqfiD6pFuwTLwz5ExLz85bT9/lzHO0pgfPd0ne4Nllawo/pjUmgYyLdnS7xULNr+GfIxiPy0+mdgDqN9z0sNHwxBJ9dVsmYAOgPjHZZaYq2DJjzrYig==